name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install jq (for parsing JSON)
      - name: Install jq
        run: sudo apt-get install jq

      # Step 3: Modify index.html based on JSON
      - name: Modify index.html based on JSON
        run: |
          A=$(jq '.A' my_dict.json)
          echo "A value: $A"
          
          if [ "$A" -lt 3 ]; then
            B=$(jq '.B' my_dict.json)
            echo "Using value B: $B"
            echo "<h1>The value of B is: $B</h1>" > index.html
          else
            C=$(jq '.C' my_dict.json)
            echo "Using value C: $C"
            echo "<h1>The value of C is: $C</h1>" > index.html
          fi

      # Step 4: Commit and push the changes to the main branch
      - name: Commit and push changes to main
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "GitHub Actions"
          author_email: "github-actions@github.com"
          message: "Deploy updated index.html"
          add: "index.html"
          push: true
          branch: main

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

