name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow when there is a push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install jq (for parsing JSON)
      - name: Install jq
        run: sudo apt-get install jq

      # Read the value of A from data.json and modify index.html accordingly
      - name: Modify index.html based on JSON
        run: |
          # Read value of A from data.json
          A=$(jq '.A' data.json)
          echo "A value: $A"

          # Modify the content of index.html based on the value of A
          if [ "$A" -lt 3 ]; then
            B=$(jq '.B' data.json)
            echo "Using value B: $B"
            echo "<h1>The value of B is: $B</h1>" > index.html
          else
            C=$(jq '.C' data.json)
            echo "Using value C: $C"
            echo "<h1>The value of C is: $C</h1>" > index.html
          fi

      # Commit changes and push to main branch
      - name: Commit and push changes to main
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "GitHub Actions"
          author_email: "github-actions@github.com"
          message: "Deploy updated index.html"
          add: "index.html"
          push: true
          branch: main
